pipeline
{
    agent any
    environment {
        LOCAL_BRANCH=local_branch
    }
    stages
    {
        stage('Start')
        {
            steps
            {
                echo "Start Pipeline for a Fix"
            }
        }
        stage('Availability Check')
        {
            steps
            {
                echo "Check if all required Tests, Modules, Reviews  and Designs of the feature are available "
                sh('''
                    ./exec/scripts/ci/check_av.sh
                ''')
            }
        }
        stage('Build')
        {
            steps
            {
                echo "Build Project"
                sh('''
                    ./exec/scripts/ci/build.sh
                ''')
            }
        }
        stage('Test & Analysis')
        {
            parallel
            {
                stage('Static Analysis')
                {
                    steps
                    {
                        echo "Static Analysis"
                        sh('''
                            ./exec/scripts/ci/staticAnalysis.sh
                        ''')
                    }
                }
                stage('Module Test (off target)')
                {
                    steps
                    {
                        echo "Module Test (off Target)"
                        sh('''
                            ./exec/scripts/ci/Mtest_offT.sh
                        ''')
                    }
                }
                stage('Module Test (on target)')
                {
                    steps
                    {
                        echo "Module Test (on Target)"
                        sh('''
                            Mtest_onT.sh
                        ''')
                    }
                }
            }
        }
        stage('Deploy')
        {
            steps
            {
                echo "Deploy" 
            }
        }
    }
    post
    {
        always {
            echo 'Clean Up the workspace'
            deleteDir()
        }
        success {
            echo 'The pipe succeded'
        }
        unstable {
            echo 'The pipe is unstable'
        }
        failure {
            echo 'the pipe failed'
        }
    }
}